// Barangay Demographics Data
export const demographicsData = [
  {
    category: "population",
    label: "Total Population",
    value: 24571,
    icon: "👥",
    order: 1,
  },
  {
    category: "land",
    label: "Land Area (hectares)",
    value: 1200,
    icon: "🗺️",
    order: 2,
  },
  {
    category: "households",
    label: "Households",
    value: 7680,
    icon: "🏠",
    order: 3,
  },
  {
    category: "voters",
    label: "Registered Voters",
    value: 9370,
    icon: "🗳️",
    order: 4,
  },
  {
    category: "precincts",
    label: "Precincts",
    value: 102,
    icon: "📍",
    order: 5,
  },
  {
    category: "families",
    label: "Families",
    value: 5852,
    icon: "👨‍👩‍👧‍👦",
    order: 6,
  },
  {
    category: "male",
    label: "Male",
    value: 10566,
    icon: "👨",
    order: 7,
  },
  {
    category: "female",
    label: "Female",
    value: 14005,
    icon: "👩",
    order: 8,
  },
  {
    category: "married",
    label: "Married",
    value: 16823,
    icon: "💑",
    order: 9,
  },
  {
    category: "unmarried",
    label: "Unmarried",
    value: 5471,
    icon: "👤",
    order: 10,
  },
  {
    category: "filipino",
    label: "Filipino",
    value: 24570,
    icon: "🇵🇭",
    order: 11,
  },
  {
    category: "foreigner",
    label: "Foreigner",
    value: 1,
    icon: "🌍",
    order: 12,
  },
  {
    category: "indigenous",
    label: "Indigenous People (IPs)",
    value: 693,
    icon: "🏔️",
    order: 13,
  },
];
